package com.wangjulong.cp5.db;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

/**
 * 数据库类
 * Created by Administrator on 2016/9/21.
 */
@DatabaseTable(tableName = "lotteries")
public class Lottery {
    // id is generated by the database and set on the object automagically
    @DatabaseField(id = true)
    int serial;
    @DatabaseField(canBeNull = false)
    int title;
    @DatabaseField(canBeNull = false)
    int n1;
    @DatabaseField(canBeNull = false)
    int n2;
    @DatabaseField(canBeNull = false)
    int n3;
    @DatabaseField(canBeNull = false)
    int n4;
    @DatabaseField(canBeNull = false)
    int n5;

    public Lottery() {
    }

    public Lottery(int serial, int title, int n1, int n2, int n3, int n4, int n5) {
        this.serial = serial;
        this.title = title;
        this.n1 = n1;
        this.n2 = n2;
        this.n3 = n3;
        this.n4 = n4;
        this.n5 = n5;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("id=").append(serial);
        sb.append(", ").append("title=").append(title);
        sb.append(", ").append("n1=").append(n1);
        sb.append(", ").append("n2=").append(n2);
        sb.append(", ").append("n3=").append(n3);
        sb.append(", ").append("n4=").append(n4);
        sb.append(", ").append("n5=").append(n5);

        return sb.toString();
    }

    public int getSerial() {
        return serial;
    }

    public void setSerial(int serial) {
        this.serial = serial;
    }

    public int getTitle() {
        return title;
    }

    public void setTitle(int title) {
        this.title = title;
    }

    public int getN1() {
        return n1;
    }

    public void setN1(int n1) {
        this.n1 = n1;
    }

    public int getN2() {
        return n2;
    }

    public void setN2(int n2) {
        this.n2 = n2;
    }

    public int getN3() {
        return n3;
    }

    public void setN3(int n3) {
        this.n3 = n3;
    }

    public int getN4() {
        return n4;
    }

    public void setN4(int n4) {
        this.n4 = n4;
    }

    public int getN5() {
        return n5;
    }

    public void setN5(int n5) {
        this.n5 = n5;
    }
}
